webpackJsonp([1],{

/***/ 16:
/***/ function(module, exports) {

	module.exports = "<div class=\"row\">\n    <div class=\"col-md-6\">\n        <table class=\"table\">\n            <thead>\n            <tr>\n                <th>#</th>\n                <th>First Name</th>\n                <th>Last Name</th>\n                <th>Username</th>\n            </tr>\n            </thead>\n            <tbody>\n            <tr>\n                <td>1</td>\n                <td>Mark</td>\n                <td>Otto</td>\n                <td>@mdo</td>\n            </tr>\n            <tr>\n                <td>2</td>\n                <td>Jacob</td>\n                <td>Thornton</td>\n                <td>@fat</td>\n            </tr>\n            <tr>\n                <td>3</td>\n                <td>Larry</td>\n                <td>the Bird</td>\n                <td>@twitter</td>\n            </tr>\n            </tbody>\n        </table>\n    </div>\n    <div class=\"col-md-6\">\n        <table class=\"table table-striped\">\n            <thead>\n            <tr>\n                <th>#</th>\n                <th>First Name</th>\n                <th>Last Name</th>\n                <th>Username</th>\n            </tr>\n            </thead>\n            <tbody>\n            <tr>\n                <td>1</td>\n                <td>Mark</td>\n                <td>Otto</td>\n                <td>@mdo</td>\n            </tr>\n            <tr>\n                <td>2</td>\n                <td>Jacob</td>\n                <td>Thornton</td>\n                <td>@fat</td>\n            </tr>\n            <tr>\n                <td>3</td>\n                <td>Larry</td>\n                <td>the Bird</td>\n                <td>@twitter</td>\n            </tr>\n            </tbody>\n        </table>\n    </div>\n</div>\n<div class=\"page-header\">\n    <h1>System Overview</h1>\n</div>\n<div class=\"row\">\n    <div class=\"col-md-8\">\n        <div ng-controller=\"GaugeDemoCtrl as GaugeDemoVm\">\n            <im-map-gauge val=\"GaugeDemoVm.val\" map-width=\"{{GaugeDemoVm.width}}\" map-height=\"{{GaugeDemoVm.height}}\" />\n        </div>\n    </div>\n</div>";

/***/ }

});